<?php
$basePath = $this->basePath();
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>ZendSkeletonHeavy</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="<?= $basePath ?>/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="<?= $basePath ?>/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="<?= $basePath ?>/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="<?= $basePath ?>/css/animations.css" media="screen" rel="stylesheet" type="text/css">
        <link href="<?= $basePath ?>/css/jqui/jquery-ui-1.10.0.custom.css" media="screen" rel="stylesheet" type="text/css">
        <link href="<?= $basePath ?>/js/select2-3.4.4/select2.css" media="screen" rel="stylesheet" type="text/css">
        <link href="<?= $basePath ?>/css/styles.css" media="screen" rel="stylesheet" type="text/css">
        <?= $this->headLink(); ?>

        <script type="text/javascript" src="<?= $basePath ?>/js/jquery-2.0.3.min.js"></script>
        <script type="text/javascript" src="<?= $basePath ?>/js/jquery-ui-1.10.3.custom.min.js"></script>
        <script type="text/javascript" src="<?= $basePath ?>/js/jquery-ui-i18n.min.js"></script>
        <script type="text/javascript" src="<?= $basePath ?>/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?= $basePath ?>/js/select2-3.4.4/select2.js"></script>
        <?= $this->headScript(); ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
